# Generated by Django 5.0.6 on 2025-06-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gsmnumber',
            field=models.IntegerField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profilepicture', verbose_name='Profil Fotoğrafı'),
        ),
    ]
