# Generated by Django 5.0.6 on 2025-07-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gsmnumber',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
