# Generated by Django 5.0.6 on 2025-05-19 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Araba Markası',
                'verbose_name_plural': 'Araba Markaları',
            },
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('part1', 'Ön Tampon'), ('part2', 'Kaput'), ('part3', 'Sağ Ön Çamurluk'), ('part4', 'Sol Ön Çamurluk'), ('part5', 'Sağ Ön Kapı'), ('part6', 'Sol Ön Kapı'), ('part7', 'Sağ Arka Kapı'), ('part8', 'Sol Arka Kapı'), ('part9', 'Sağ Arka Çamurluk'), ('part10', 'Sol Arka Çamurluk'), ('part11', 'Arka Tampon'), ('part12', 'Bagaj Kapağı'), ('part13', 'Tavan')], max_length=200)),
                ('damagetype', models.CharField(choices=[('painted', 'Boyalı'), ('locally', 'Lokal Boyalı'), ('changing', 'Değişen')], max_length=20)),
            ],
            options={
                'verbose_name': 'Hasarlı Parça',
                'verbose_name_plural': 'Hasarlı Parçalar',
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fueltype', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Yakıt Türü',
                'verbose_name_plural': 'Yakıt Türleri',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'Araç İlan Resmi',
                'verbose_name_plural': 'Araç İlan Resimleri',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100)),
                ('modelyear', models.IntegerField()),
                ('enginesize', models.IntegerField()),
                ('enginepower', models.CharField(max_length=6)),
                ('image', models.ImageField(upload_to='media/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.carbrand')),
                ('fueltype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.fueltype')),
            ],
            options={
                'verbose_name': 'Araba Modeli',
                'verbose_name_plural': 'Araba Modelleri',
            },
        ),
        migrations.CreateModel(
            name='CarSaleAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adname', models.CharField(max_length=150)),
                ('startingprice', models.IntegerField()),
                ('tramer', models.IntegerField(blank=True, null=True)),
                ('numberplate', models.CharField(blank=True, max_length=10, null=True)),
                ('adescription', models.TextField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.carbrand')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.carmodel')),
                ('damage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.damage')),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.images')),
            ],
            options={
                'verbose_name': 'Araba İlanı',
                'verbose_name_plural': 'Araba İlanları',
            },
        ),
    ]
