# Generated by Django 5.0.6 on 2025-05-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_carsalead_targetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
