# Generated by Django 5.0.6 on 2025-06-06 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_carsalead_damage_remove_carsalead_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='ad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.carsalead'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='ad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='shop.carsalead'),
            preserve_default=False,
        ),
    ]
