# Generated by Django 5.0.6 on 2025-06-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_damage_ad_images_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsalead',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
