# Generated by Django 5.0.6 on 2025-06-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_carsalead_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsalead',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
