# Generated by Django 5.0.6 on 2025-07-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_carsalead_is_active_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Fiyat Teklifi', 'verbose_name_plural': 'Fiyat Teklifleri'},
        ),
    ]
